name: Deploy chat script to S3 prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run build
        env:
          VITE_BACKEND_URL: ${{ secrets.PROD_BACKEND_URL }}
          VITE_CDN_URL: https://${{ secrets.PROD_S3_BUCKET }}
      
      - run: bun run build:css

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
          S3_BUCKET: ${{ secrets.PROD_S3_BUCKET }}
        run: |
          bun install -g aws-cli
          aws s3 cp ./dist/chat.js s3://$S3_BUCKET/chat.js
          aws s3 cp ./dist/style.css s3://$S3_BUCKET/style.css
          aws cloudfront create-invalidation --distribution-id ${{ secrets.PROD_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/chat.js" "/style.css"
